using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace RestaurantGorRahsa.Models
{
    public class ModelMeal
    {
        public ModelMeal() {
            lstItems = new HashSet<ModelItem>();
        }

        [Key]
      //  [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Automatically generated by DB
        public int ID { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        public string Name { get; set; }

        public string? ImageName { get; set; }

        [Required(ErrorMessage = "Offered number is required.")]
        public int OfferedNumber { get; set; }

        [Required(ErrorMessage = "Price is required.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Price must be greater than 0.")]
        public float price { get; set; }

        [Required(ErrorMessage = "Type ID is required.")]
        public int TypeID { get; set; }

        [ForeignKey("TypeID")]
        [ValidateNever]

        public Models.ModelType type { get; set; }

        [JsonIgnore]
        public  ICollection<ModelItem> lstItems { get; set; }

    }

}
